### ISSUE TITLE
Ensure reproducibility of image production runs

### ISSUE THREAD

**Issue by aboucaud** [LSSTDESC/BlendingToolKit#69] opened 2020-12-02 17:26 UTC
Reproduce results obtained by the various BTK steps would be a real added value.

So far the introductory notebook makes use of `numpy.random.seed()` but because many generators are involved, we should probably use something more scalable like passing around a random generator like `numpy.random.RandomState()`.

**Comment by thuiop** [comment] 2020-12-02 18:45
I agree ; actually, when we overhauled BTK in August, the tests broke because they were only using a seed to get reproducible results. My take on this was to allow the users to specify some galaxy ids and shifts to get some more reproducible results, but we still rely on the seed for some things (noise in particular).

**Comment by ismael-mendoza** [comment] 2021-10-06 02:04
Reopened based on additional comments in #226  from @aboucaud

**Comment by thuiop** [comment] 2021-12-06 23:07
While working on the shear PR, I've come to realize that there are still some issues : 
- the noise_seed is set per minibatch, instead of per blend, which is probably not a good idea
- the noise realisation is dependent not only on the seed, but also on the base image ; that is two different blends will get a (partially) different noise for a same random seed. I am also not sure that this is the expected behaviour, although it might be : I believe this is caused by the fact that the Poisson noise uses the values of the pixels as expectations for the noise ; it will therefore add more noise to the galaxy itself. Is that the expected behaviour ?

**Comment by thuiop** [comment] 2021-12-07 17:30
I discussed the second issue with @aguinot ; it seems that generating the noise from the background apart from the noise on the galaxy flux may be preferable (apparently ImSim does it ?). The galaxy flux noise can be simulated by drawing it with the method `phot`, although we might be fine ignoring it completely. It would be good to have other opinions before proceding.

**Comment by ismael-mendoza** [comment] 2021-12-08 16:45
Hi @thuiop thanks for bringing this up and reopening the issue. We definitely don't want any bugs in the reproducibility aspect of the codebase. 

> the noise_seed is set per minibatch, instead of per blend, which is probably not a good idea

Yeah this makes some sense. Do you have a suggestion for how to fix this? Perhaps passing around an rng to each minibatch rather than a noise seed directly?

**Comment by aguinot** [comment] 2021-12-16 16:27
I actually discovered the behavior of the `addNoise` method which I never used before. I see your point Ismael and you are right. Yet, I think it is better in some cases (like what we are trying to do here with the shear) to control the background noise and the sampling of the flux in separate method. For example in our case we would like the light profile to only have variations due to different shear values and the exact same noise apply to both images. Also Galsim has a method to actually sample the light profile when you draw it using `method=phot` (at the end I am not sure it will make a big difference compare to what you are doing, except it is probably slower and require more parameters.. But there is go reasons to use this method, especially when you want some instrumental effects).
Any way, in my opinion it would be more clear to separate both. Also it might not be obvious for users that adding noise to the image will imply also the resampling of the light profile.

**Comment by ismael-mendoza** [comment] 2022-01-05 16:36
Hi @thuiop and @aguinot, thanks for your heplful discussion. I'm hoping to revive this thread now that I'm back from break :) Maybe we can discuss in the next meeting the details of adding noise to background and flux separately? I think your explanations make sense and I'm happy to proceed with that though. 

I think that @thuiop first point is solved by #249 so we can merge that soon??

**Comment by thuiop** [comment] 2022-01-21 16:43
I believe the problem should be gone with the PR #254 , thus I am closing this issue.

**Comment by ismael-mendoza** [comment] 2022-02-04 17:49
I think you forgot to close this @thuiop

**Closed by ismael-mendoza** 2022-02-04 17:49 UTC

**Comment by thuiop** [comment] 2022-02-04 18:02
Thank you, I thought I already did it.
