### ISSUE TITLE
augment data bug

### ISSUE THREAD

**Issue by b-biswas** [LSSTDESC/BlendingToolKit#419] opened 2023-07-12 13:54 UTC
it looks like augment data is rotating galaxies differently in different bands:
For example, here is a [plot](https://github.com/b-biswas/BlendingToolKit/blob/check-rotation/notebooks/rotation_bug.ipynb)  for the same field in 2 different bands. 
Also, `blend_list` stores rotation information only in the last band.

**Comment by ismael-mendoza** [comment] 2023-07-12 20:55
Basically the problem is in the CatsimCatalog class only, it happens because when we do the for loop over the bands we change entry[`pa_bulge`] / entry[`pa_disk`] by adding `btk_rotation`. The entry stays saved inside the catalog object so in every band we add the rotation angle again and it keeps accumulating

The easiest solution is just to update the `entry` outside the for loop of the bands. @aguinot also suggested to avoid having the `if` statement more than once by creating an all zeroe `btk_rotation` column in the case that `augment_data = False`.

**Comment by ismael-mendoza** [comment] 2023-08-13 18:30
Fixed in #412

**Closed by ismael-mendoza** 2023-08-13 18:30 UTC
Labels: bug
